<?php
/**
 * Database Connection & Migration Handler
 * Supports MySQL PDO with automatic SQLite fallback for zero-friction setup.
 */

// Set Indonesian Western Time (WIB / Asia/Jakarta, UTC+7) globally
if (function_exists('date_default_timezone_set')) {
    date_default_timezone_set('Asia/Jakarta');
}

class Database {
    private static ?PDO $pdo = null;
    private static string $driverType = 'mysql';
    private static bool $isMigrated = false;

    public static function getConnection(): PDO {
        if (self::$pdo !== null) {
            try {
                self::$pdo->query("SELECT 1");
                return self::$pdo;
            } catch (Throwable $e) {
                self::$pdo = null;
            }
        }

        // Load production config if present (e.g. generated by GitHub Actions or placed on server)
        if (file_exists(__DIR__ . '/config.php')) {
            require_once __DIR__ . '/config.php';
        }

        $host     = defined('DB_HOST') ? DB_HOST : (getenv('DB_HOST') ?: '127.0.0.1');
        $port     = defined('DB_PORT') ? DB_PORT : (getenv('DB_PORT') ?: '3306');
        $dbName   = defined('DB_NAME') ? DB_NAME : (getenv('DB_NAME') ?: 'ocs_inventory');
        $username = defined('DB_USER') ? DB_USER : (getenv('DB_USER') ?: 'root');
        $password = defined('DB_PASS') ? DB_PASS : (getenv('DB_PASS') ?: '');

        // Try MySQL First
        try {
            // 1. First try direct connection to target DB (works on InfinityFree / shared hosting where CREATE DATABASE is restricted)
            self::$pdo = new PDO("mysql:host=$host;port=$port;dbname=$dbName;charset=utf8mb4", $username, $password, [
                PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
                PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
                PDO::ATTR_TIMEOUT => 5
            ]);
            try { self::$pdo->exec("SET time_zone = '+07:00';"); } catch (Throwable $tzE) {}
            self::$driverType = 'mysql';
        } catch (Exception $eDirect) {
            // 2. If DB does not exist (e.g. fresh local XAMPP setup), try creating it
            try {
                $initPdo = new PDO("mysql:host=$host;port=$port", $username, $password, [
                    PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
                    PDO::ATTR_TIMEOUT => 3
                ]);
                $initPdo->exec("CREATE DATABASE IF NOT EXISTS `$dbName` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;");
                
                self::$pdo = new PDO("mysql:host=$host;port=$port;dbname=$dbName;charset=utf8mb4", $username, $password, [
                    PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
                    PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC
                ]);
                try { self::$pdo->exec("SET time_zone = '+07:00';"); } catch (Throwable $tzE) {}
                self::$driverType = 'mysql';
            } catch (Exception $eInit) {
                // 3. Fallback to SQLite if MySQL is offline
                $sqlitePath = __DIR__ . '/ocs_inventory.sqlite';
                self::$pdo = new PDO("sqlite:" . $sqlitePath, null, null, [
                    PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
                    PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC
                ]);
                self::$driverType = 'sqlite';
            }
        }

        if (!self::$isMigrated) {
            self::migrateTables();
            self::$isMigrated = true;
        }
        return self::$pdo;
    }

    public static function getDriverType(): string {
        return self::$driverType;
    }

    private static function migrateTables(): void {
        $pdo = self::$pdo;

        $schemaVersion = '20260910_v2';
        try {
            $check = $pdo->prepare("SELECT key_value FROM system_settings WHERE key_name = 'db_schema_version'");
            $check->execute();
            if ($check->fetchColumn() === $schemaVersion) {
                return;
            }
        } catch (Throwable $e) {
            // First run or system_settings table not created yet
        }

        if (self::$driverType === 'mysql') {
            // Table: users
            $pdo->exec("CREATE TABLE IF NOT EXISTS `users` (
                `id` INT AUTO_INCREMENT PRIMARY KEY,
                `username` VARCHAR(50) NOT NULL UNIQUE,
                `password` VARCHAR(255) NOT NULL,
                `full_name` VARCHAR(100) NOT NULL,
                `role` VARCHAR(50) NOT NULL DEFAULT 'operator',
                `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;");

            // Table: sku_rack_locations (Mapping Bin Code -> SKU)
            $pdo->exec("CREATE TABLE IF NOT EXISTS `sku_rack_locations` (
                `id` INT AUTO_INCREMENT PRIMARY KEY,
                `bin_code` VARCHAR(50) NOT NULL,
                `rack_name` VARCHAR(50) NOT NULL,
                `sku` VARCHAR(100) NOT NULL,
                `barcode` VARCHAR(100) DEFAULT NULL,
                `product_name` VARCHAR(255) NOT NULL,
                `category` VARCHAR(100) DEFAULT NULL,
                `notes` TEXT DEFAULT NULL,
                `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
                `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                UNIQUE KEY `uniq_bin_sku` (`bin_code`, `sku`),
                INDEX (`sku`),
                INDEX (`bin_code`)
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;");

            // Table: stock_master (Synced stock cache from OCS)
            $pdo->exec("CREATE TABLE IF NOT EXISTS `stock_master` (
                `id` INT AUTO_INCREMENT PRIMARY KEY,
                `sku` VARCHAR(100) NOT NULL UNIQUE,
                `barcode` VARCHAR(100) DEFAULT NULL,
                `product_name` VARCHAR(255) NOT NULL,
                `area_id` VARCHAR(50) DEFAULT 'Pusat',
                `sap_code` VARCHAR(100) DEFAULT NULL,
                `category` VARCHAR(100) DEFAULT NULL,
                `qty_on_hand` INT DEFAULT 0,
                `qty_available` INT DEFAULT 0,
                `qty_gudang_kecil` INT DEFAULT 0,
                `qty_gudang_besar` INT DEFAULT 0,
                `is_active` TINYINT(1) DEFAULT 1,
                `last_synced_at` DATETIME DEFAULT CURRENT_TIMESTAMP
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;");

            // Table: replenish_requests
            $pdo->exec("CREATE TABLE IF NOT EXISTS `replenish_requests` (
                `id` INT AUTO_INCREMENT PRIMARY KEY,
                `request_no` VARCHAR(50) NOT NULL UNIQUE,
                `bin_code` VARCHAR(50) NOT NULL,
                `sku` VARCHAR(100) NOT NULL,
                `product_name` VARCHAR(255) NOT NULL,
                `barcode` VARCHAR(100) DEFAULT NULL,
                `qty_gudang_kecil` INT DEFAULT 0,
                `qty_gudang_besar` INT DEFAULT 0,
                `qty_request` INT NOT NULL,
                `requested_by` VARCHAR(100) NOT NULL,
                `status` ENUM('PENDING', 'APPROVED', 'REJECTED', 'COMPLETED') NOT NULL DEFAULT 'PENDING',
                `admin_notes` TEXT DEFAULT NULL,
                `processed_by` VARCHAR(100) DEFAULT NULL,
                `rack_gudang_besar` VARCHAR(100) DEFAULT NULL,
                `batch_number` VARCHAR(100) DEFAULT NULL,
                `picked_qty` INT DEFAULT NULL,
                `picked_by` VARCHAR(100) DEFAULT NULL,
                `picked_at` DATETIME DEFAULT NULL,
                `assigned_to` VARCHAR(100) DEFAULT NULL,
                `done_ocs` TINYINT(1) DEFAULT 0,
                `done_wms` TINYINT(1) DEFAULT 0,
                `done_ocs_at` DATETIME DEFAULT NULL,
                `done_wms_at` DATETIME DEFAULT NULL,
                `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
                `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;");

            // Table: system_settings
            $pdo->exec("CREATE TABLE IF NOT EXISTS `system_settings` (
                `key_name` VARCHAR(50) PRIMARY KEY,
                `key_value` TEXT NOT NULL,
                `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;");

        } else {
            // SQLite Syntax
            $pdo->exec("CREATE TABLE IF NOT EXISTS users (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                username TEXT NOT NULL UNIQUE,
                password TEXT NOT NULL,
                full_name TEXT NOT NULL,
                role TEXT NOT NULL DEFAULT 'operator',
                created_at DATETIME DEFAULT CURRENT_TIMESTAMP
            );");

            $pdo->exec("CREATE TABLE IF NOT EXISTS sku_rack_locations (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                bin_code TEXT NOT NULL,
                rack_name TEXT NOT NULL,
                sku TEXT NOT NULL,
                barcode TEXT,
                product_name TEXT NOT NULL,
                category TEXT,
                notes TEXT,
                created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
                updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
                UNIQUE (bin_code, sku)
            );");

            $pdo->exec("CREATE TABLE IF NOT EXISTS stock_master (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                sku TEXT NOT NULL UNIQUE,
                barcode TEXT,
                product_name TEXT NOT NULL,
                area_id TEXT DEFAULT 'Pusat',
                sap_code TEXT,
                category TEXT,
                qty_on_hand INTEGER DEFAULT 0,
                qty_available INTEGER DEFAULT 0,
                qty_gudang_kecil INTEGER DEFAULT 0,
                qty_gudang_besar INTEGER DEFAULT 0,
                is_active INTEGER DEFAULT 1,
                last_synced_at DATETIME DEFAULT CURRENT_TIMESTAMP
            );");

            $pdo->exec("CREATE TABLE IF NOT EXISTS replenish_requests (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                request_no TEXT NOT NULL UNIQUE,
                bin_code TEXT NOT NULL,
                sku TEXT NOT NULL,
                product_name TEXT NOT NULL,
                barcode TEXT,
                qty_gudang_kecil INTEGER DEFAULT 0,
                qty_gudang_besar INTEGER DEFAULT 0,
                qty_request INTEGER NOT NULL,
                requested_by TEXT NOT NULL,
                status TEXT NOT NULL DEFAULT 'PENDING',
                admin_notes TEXT,
                processed_by TEXT,
                rack_gudang_besar TEXT,
                batch_number TEXT,
                picked_qty INTEGER,
                picked_by TEXT,
                picked_at DATETIME,
                assigned_to TEXT,
                done_ocs INTEGER DEFAULT 0,
                done_wms INTEGER DEFAULT 0,
                done_ocs_at DATETIME,
                done_wms_at DATETIME,
                created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
                updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
            );");

            $pdo->exec("CREATE TABLE IF NOT EXISTS system_settings (
                key_name TEXT PRIMARY KEY,
                key_value TEXT NOT NULL,
                updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
            );");
        }

        // ---------------------------------------------------------------
        // Migration: sku_rack_locations used to declare bin_code UNIQUE on its
        // own. One bin in OCS can hold several SKUs (21 such bins in EJI_WMS),
        // so every sync aborted on a duplicate-key error and rolled back all
        // rows. The natural key is (bin_code, sku) — rebuild older databases.
        // ---------------------------------------------------------------
        self::migrateSkuRackUniqueKey();
        self::migrateReplenishRequestColumns();

        // Seed default users if empty or missing new roles
        self::seedDefaultUsers();

        // Sync data from ocs_inventory.sqlite if running on MySQL and SQLite has newer/initial data
        if (self::$driverType === 'mysql') {
            self::syncSqliteToMysql();
        }

        // Seed initial SKU-Rack demo data if still empty (fallback if no sqlite data exists)
        $stmt = $pdo->query("SELECT COUNT(*) as cnt FROM sku_rack_locations");
        $rackCount = (int)($stmt->fetch()['cnt'] ?? 0);
        if ($rackCount === 0) {
            $insertRack = $pdo->prepare("INSERT INTO sku_rack_locations (bin_code, rack_name, sku, barcode, product_name, category) VALUES (?, ?, ?, ?, ?, ?)");
            $sampleRacks = [
                ['BIN-A01-01', 'Rak A - Level 1', 'SKU-EJI-001', '899123456001', 'Oli Mesin Synth 10W-40 1L', 'Oli & Pelumas'],
                ['BIN-A01-02', 'Rak A - Level 1', 'SKU-EJI-002', '899123456002', 'Filter Udara Matic 125cc', 'Sparepart Fast Moving'],
                ['BIN-B02-01', 'Rak B - Level 2', 'SKU-EJI-003', '899123456003', 'Busi Super Iridium CR7', 'Pengapian'],
                ['BIN-B02-02', 'Rak B - Level 2', 'SKU-EJI-004', '899123456004', 'Kampas Rem Depan Cakram', 'Pengereman'],
                ['BIN-C03-01', 'Rak C - Level 3', 'SKU-EJI-005', '899123456005', 'V-Belt Drive Pulley Set', 'Transmisi CVT'],
                ['BIN-C03-02', 'Rak C - Level 3', 'SKU-EJI-006', '899123456006', 'Aki Kering Maintenance Free 12V 5Ah', 'Kelistrikan'],
            ];
            foreach ($sampleRacks as $r) {
                $insertRack->execute($r);
            }

            // Seed initial stock master
            $insertStock = $pdo->prepare("INSERT INTO stock_master (sku, barcode, product_name, area_id, sap_code, qty_on_hand, qty_available, qty_gudang_kecil, qty_gudang_besar) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)");
            $sampleStocks = [
                ['SKU-EJI-001', '899123456001', 'Oli Mesin Synth 10W-40 1L', 'Area-Utama', 'SAP-1001', 150, 140, 15, 125],
                ['SKU-EJI-002', '899123456002', 'Filter Udara Matic 125cc', 'Area-Utama', 'SAP-1002', 80, 75, 8, 67],
                ['SKU-EJI-003', '899123456003', 'Busi Super Iridium CR7', 'Area-Utama', 'SAP-1003', 300, 280, 20, 260],
                ['SKU-EJI-004', '899123456004', 'Kampas Rem Depan Cakram', 'Area-Utama', 'SAP-1004', 45, 40, 5, 35],
                ['SKU-EJI-005', '899123456005', 'V-Belt Drive Pulley Set', 'Area-Utama', 'SAP-1005', 60, 50, 6, 44],
                ['SKU-EJI-006', '899123456006', 'Aki Kering Maintenance Free 12V 5Ah', 'Area-Utama', 'SAP-1006', 25, 20, 3, 17],
            ];
            foreach ($sampleStocks as $s) {
                $insertStock->execute($s);
            }
        }

        try {
            $up = $pdo->prepare("INSERT INTO system_settings (key_name, key_value) VALUES ('db_schema_version', ?) ON DUPLICATE KEY UPDATE key_value = VALUES(key_value)");
            $up->execute([$schemaVersion]);
        } catch (Throwable $e) {}
    }

    /**
     * Otomatis sinkronisasi master stock dan rack mapping dari ocs_inventory.sqlite
     * ke MySQL di InfinityFree setiap kali ada update file sqlite yang di-push.
     */
    private static function syncSqliteToMysql(): void
    {
        $sqlitePath = __DIR__ . '/ocs_inventory.sqlite';
        if (!file_exists($sqlitePath)) {
            return;
        }

        $sqliteMtime = (string)filemtime($sqlitePath);
        $pdo = self::$pdo;

        // Cek apakah database MySQL sudah sinkron dengan versi file sqlite ini
        try {
            $checkStmt = $pdo->prepare("SELECT key_value FROM system_settings WHERE key_name = 'last_sqlite_sync'");
            $checkStmt->execute();
            $lastSync = $checkStmt->fetchColumn();

            $countStock = (int)$pdo->query("SELECT COUNT(*) FROM stock_master")->fetchColumn();

            // Jika mtime sama dan data stock sudah ada di MySQL, tidak perlu sync ulang
            if ($lastSync === $sqliteMtime && $countStock > 0) {
                return;
            }
        } catch (Throwable $e) {
            // Lanjut jika terjadi error pembacaan settings
        }

        try {
            if (function_exists('set_time_limit')) {
                @set_time_limit(120);
            }

            $sqlitePdo = new PDO("sqlite:" . $sqlitePath, null, null, [
                PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
                PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC
            ]);

            $pdo->beginTransaction();

            // 1. Sync sku_rack_locations (670+ baris rak)
            $rStmt = $sqlitePdo->query("SELECT bin_code, rack_name, sku, barcode, product_name, category, notes FROM sku_rack_locations");
            $rInsert = $pdo->prepare("INSERT INTO sku_rack_locations (bin_code, rack_name, sku, barcode, product_name, category, notes) 
                VALUES (?, ?, ?, ?, ?, ?, ?) 
                ON DUPLICATE KEY UPDATE 
                    rack_name = VALUES(rack_name), 
                    barcode = VALUES(barcode), 
                    product_name = VALUES(product_name), 
                    category = VALUES(category), 
                    notes = VALUES(notes)");
            while ($row = $rStmt->fetch()) {
                $rInsert->execute([
                    $row['bin_code'], $row['rack_name'], $row['sku'], $row['barcode'], 
                    $row['product_name'], $row['category'], $row['notes']
                ]);
            }

            // 3. Sync stock_master (2500+ baris stok)
            $sStmt = $sqlitePdo->query("SELECT sku, barcode, product_name, area_id, sap_code, category, qty_on_hand, qty_available, qty_gudang_kecil, qty_gudang_besar, is_active FROM stock_master");
            $sInsert = $pdo->prepare("INSERT INTO stock_master (sku, barcode, product_name, area_id, sap_code, category, qty_on_hand, qty_available, qty_gudang_kecil, qty_gudang_besar, is_active) 
                VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) 
                ON DUPLICATE KEY UPDATE 
                    barcode = VALUES(barcode), 
                    product_name = VALUES(product_name), 
                    area_id = VALUES(area_id), 
                    sap_code = VALUES(sap_code), 
                    category = VALUES(category), 
                    qty_on_hand = VALUES(qty_on_hand), 
                    qty_available = VALUES(qty_available), 
                    qty_gudang_kecil = VALUES(qty_gudang_kecil), 
                    qty_gudang_besar = VALUES(qty_gudang_besar), 
                    is_active = VALUES(is_active)");
            while ($row = $sStmt->fetch()) {
                $sInsert->execute([
                    $row['sku'], $row['barcode'], $row['product_name'], $row['area_id'], 
                    $row['sap_code'], $row['category'], $row['qty_on_hand'], $row['qty_available'], 
                    $row['qty_gudang_kecil'], $row['qty_gudang_besar'], $row['is_active']
                ]);
            }

            // 4. Update riwayat sinkronisasi
            $settStmt = $pdo->prepare("INSERT INTO system_settings (key_name, key_value) VALUES ('last_sqlite_sync', ?) 
                ON DUPLICATE KEY UPDATE key_value = VALUES(key_value)");
            $settStmt->execute([$sqliteMtime]);

            $pdo->commit();
        } catch (Throwable $e) {
            if ($pdo->inTransaction()) {
                $pdo->rollBack();
            }
            error_log("Database sync from SQLite to MySQL failed: " . $e->getMessage());
        }
    }

    /**
     * Replaces the legacy UNIQUE(bin_code) constraint on sku_rack_locations
     * with UNIQUE(bin_code, sku). Safe to run on every boot: it inspects the
     * current schema first and does nothing once the new key is in place.
     */
    private static function migrateSkuRackUniqueKey(): void
    {
        $pdo = self::$pdo;

        try {
            if (self::$driverType === 'mysql') {
                $indexes = $pdo->query("SHOW INDEX FROM `sku_rack_locations`")->fetchAll();
                $hasNewKey = false;
                $legacyKeys = [];
                foreach ($indexes as $idx) {
                    if ($idx['Key_name'] === 'uniq_bin_sku') {
                        $hasNewKey = true;
                    } elseif ((int)$idx['Non_unique'] === 0 && $idx['Key_name'] !== 'PRIMARY' && $idx['Column_name'] === 'bin_code') {
                        $legacyKeys[$idx['Key_name']] = true;
                    }
                }
                if ($hasNewKey && empty($legacyKeys)) {
                    return;
                }
                foreach (array_keys($legacyKeys) as $keyName) {
                    $pdo->exec("ALTER TABLE `sku_rack_locations` DROP INDEX `" . $keyName . "`");
                }
                if (!$hasNewKey) {
                    $pdo->exec("ALTER TABLE `sku_rack_locations` ADD UNIQUE KEY `uniq_bin_sku` (`bin_code`, `sku`)");
                }
                return;
            }

            // SQLite cannot drop a column-level UNIQUE constraint, so the table
            // has to be rebuilt and the existing rows copied across.
            $ddl = $pdo->query("SELECT sql FROM sqlite_master WHERE type = 'table' AND name = 'sku_rack_locations'")->fetch();
            $ddl = $ddl['sql'] ?? '';
            if ($ddl === '' || stripos($ddl, 'UNIQUE (bin_code, sku)') !== false) {
                return;
            }

            $pdo->exec("PRAGMA foreign_keys = OFF");
            $pdo->exec("CREATE TABLE sku_rack_locations_new (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                bin_code TEXT NOT NULL,
                rack_name TEXT NOT NULL,
                sku TEXT NOT NULL,
                barcode TEXT,
                product_name TEXT NOT NULL,
                category TEXT,
                notes TEXT,
                created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
                updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
                UNIQUE (bin_code, sku)
            )");
            $pdo->exec("INSERT INTO sku_rack_locations_new (id, bin_code, rack_name, sku, barcode, product_name, category, notes, created_at, updated_at)
                        SELECT id, bin_code, rack_name, sku, barcode, product_name, category, notes, created_at, updated_at FROM sku_rack_locations");
            $pdo->exec("DROP TABLE sku_rack_locations");
            $pdo->exec("ALTER TABLE sku_rack_locations_new RENAME TO sku_rack_locations");
            $pdo->exec("CREATE INDEX IF NOT EXISTS idx_sku_rack_sku ON sku_rack_locations (sku)");
            $pdo->exec("CREATE INDEX IF NOT EXISTS idx_sku_rack_bin ON sku_rack_locations (bin_code)");
            $pdo->exec("PRAGMA foreign_keys = ON");
        } catch (Exception $e) {
            // A failed migration must not take the whole app down; the sync
            // handler reports the duplicate-key error if this could not run.
            error_log('sku_rack_locations unique-key migration failed: ' . $e->getMessage());
        }
    }

    /**
     * Pastikan kolom rack_gudang_besar, batch_number, picked_qty, picked_by, picked_at
     * sudah tersedia di tabel replenish_requests (aman untuk MySQL dan SQLite).
     */
    private static function migrateReplenishRequestColumns(): void
    {
        $pdo = self::$pdo;
        try {
            $existingColumns = [];
            if (self::$driverType === 'mysql') {
                $stmt = $pdo->query("SHOW COLUMNS FROM `replenish_requests`");
                while ($col = $stmt->fetch()) {
                    $existingColumns[strtolower($col['Field'])] = true;
                }
            } else {
                $stmt = $pdo->query("PRAGMA table_info(replenish_requests)");
                while ($col = $stmt->fetch()) {
                    $existingColumns[strtolower($col['name'])] = true;
                }
            }

            $neededCols = [
                'rack_gudang_besar' => self::$driverType === 'mysql' ? 'VARCHAR(100) DEFAULT NULL' : 'TEXT',
                'batch_number'      => self::$driverType === 'mysql' ? 'VARCHAR(100) DEFAULT NULL' : 'TEXT',
                'picked_qty'        => self::$driverType === 'mysql' ? 'INT DEFAULT NULL' : 'INTEGER',
                'picked_by'         => self::$driverType === 'mysql' ? 'VARCHAR(100) DEFAULT NULL' : 'TEXT',
                'picked_at'         => self::$driverType === 'mysql' ? 'DATETIME DEFAULT NULL' : 'DATETIME',
                'assigned_to'       => self::$driverType === 'mysql' ? 'VARCHAR(100) DEFAULT NULL' : 'TEXT',
                'done_ocs'          => self::$driverType === 'mysql' ? 'TINYINT(1) DEFAULT 0' : 'INTEGER DEFAULT 0',
                'done_wms'          => self::$driverType === 'mysql' ? 'TINYINT(1) DEFAULT 0' : 'INTEGER DEFAULT 0',
                'done_ocs_at'       => self::$driverType === 'mysql' ? 'DATETIME DEFAULT NULL' : 'DATETIME',
                'done_wms_at'       => self::$driverType === 'mysql' ? 'DATETIME DEFAULT NULL' : 'DATETIME',
            ];

            foreach ($neededCols as $colName => $colDef) {
                if (!isset($existingColumns[$colName])) {
                    $pdo->exec("ALTER TABLE " . (self::$driverType === 'mysql' ? "`replenish_requests`" : "replenish_requests") . " ADD COLUMN {$colName} {$colDef}");
                }
            }

            // Ensure status and role are VARCHAR(50) in MySQL to support 'CANCELLED' and 'superadmin'
            if (self::$driverType === 'mysql') {
                try {
                    $pdo->exec("ALTER TABLE `users` MODIFY COLUMN `role` VARCHAR(50) NOT NULL DEFAULT 'operator'");
                } catch (Throwable $e) {}
                try {
                    $pdo->exec("ALTER TABLE `replenish_requests` MODIFY COLUMN `status` VARCHAR(50) NOT NULL DEFAULT 'PENDING'");
                } catch (Throwable $e) {}
            }
        } catch (Throwable $e) {
            error_log('migrateReplenishRequestColumns error: ' . $e->getMessage());
        }
    }

    /**
     * Seed akun bawaan untuk Administrator, Operator Gudang Kecil, dan Operator Gudang Besar
     */
    private static function seedDefaultUsers(): void
    {
        $pdo = self::$pdo;
        try {
            // Check if initial users have already been seeded.
            // If already seeded, NEVER re-insert deleted users!
            $settingStmt = $pdo->query("SELECT key_value FROM system_settings WHERE key_name = 'default_users_seeded'");
            $alreadySeeded = $settingStmt ? $settingStmt->fetchColumn() : false;

            if ($alreadySeeded === '1') {
                // System already seeded. Do not resurrect any deleted users.
                // Just verify if user 'daniel' exists; if not, create him.
                $dStmt = $pdo->prepare("SELECT id FROM users WHERE username = 'daniel'");
                $dStmt->execute();
                if (!$dStmt->fetch()) {
                    $ins = $pdo->prepare("INSERT INTO users (username, password, full_name, role) VALUES (?, ?, ?, ?)");
                    $ins->execute(['daniel', password_hash('Dh@niel013', PASSWORD_DEFAULT), 'Daniel Superadmin', 'superadmin']);
                }
                return;
            }

            // Check if table already has users
            $userCount = (int)$pdo->query("SELECT COUNT(*) FROM users")->fetchColumn();
            if ($userCount > 0) {
                // Table already has users: ensure daniel exists, then mark as seeded
                $dStmt = $pdo->prepare("SELECT id FROM users WHERE username = 'daniel'");
                $dStmt->execute();
                if (!$dStmt->fetch()) {
                    $ins = $pdo->prepare("INSERT INTO users (username, password, full_name, role) VALUES (?, ?, ?, ?)");
                    $ins->execute(['daniel', password_hash('Dh@niel013', PASSWORD_DEFAULT), 'Daniel Superadmin', 'superadmin']);
                }

                if (self::$driverType === 'mysql') {
                    $pdo->exec("INSERT INTO system_settings (key_name, key_value) VALUES ('default_users_seeded', '1') ON DUPLICATE KEY UPDATE key_value = '1'");
                } else {
                    $pdo->exec("INSERT OR REPLACE INTO system_settings (key_name, key_value) VALUES ('default_users_seeded', '1')");
                }
                return;
            }

            // Fresh database: seed defaults
            $defaultUsers = [
                [
                    'username'  => 'daniel',
                    'full_name' => 'Daniel Superadmin',
                    'role'      => 'superadmin',
                    'password'  => 'Dh@niel013'
                ],
                [
                    'username'  => 'admin',
                    'full_name' => 'Administrator Inventory',
                    'role'      => 'admin',
                    'password'  => 'admin123'
                ],
                [
                    'username'  => 'gudang_kecil',
                    'full_name' => 'Operator Gudang Kecil',
                    'role'      => 'gudang_kecil',
                    'password'  => 'operator123'
                ],
                [
                    'username'  => 'gudang_besar',
                    'full_name' => 'Operator Gudang Besar',
                    'role'      => 'gudang_besar',
                    'password'  => 'operator123'
                ],
            ];

            $insertStmt = $pdo->prepare("INSERT INTO users (username, password, full_name, role) VALUES (?, ?, ?, ?)");
            foreach ($defaultUsers as $u) {
                $insertStmt->execute([
                    $u['username'],
                    password_hash($u['password'], PASSWORD_DEFAULT),
                    $u['full_name'],
                    $u['role']
                ]);
            }

            // Mark as seeded
            if (self::$driverType === 'mysql') {
                $pdo->exec("INSERT INTO system_settings (key_name, key_value) VALUES ('default_users_seeded', '1') ON DUPLICATE KEY UPDATE key_value = '1'");
            } else {
                $pdo->exec("INSERT OR REPLACE INTO system_settings (key_name, key_value) VALUES ('default_users_seeded', '1')");
            }
        } catch (Throwable $e) {
            error_log('seedDefaultUsers error: ' . $e->getMessage());
        }
    }
}

